# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3765ff523d0557a0c691a7c6ac1eec02b6094d9d48c701054ae7a93fcbafdf021788b7d7538d1d5ba3059e62a981ef2adfeed1a5bd1f45835b42dd4cc64a6f57

test:
  secret_key_base: 3c3682a6dac319a2f80fefbc3eea3a344df6dbc69e68f9feee2ea67c2cad533132e14028741f2bc857a28fade1988341392658c168ebe437b436fd18a7df3970

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
